theme: jekyll-theme-cayman
title: "Mein Schiff Bordfinder"
description: "Die offizielle Webseite der Bordfinder Apps."
permalink: /:changelog/
github:
  is_project_page: false
footer:
  display: none
