theme: jekyll-theme-cayman
title: "Mein Schiff Bordfinder"
description: "Die offizielle Webseite der Bordfinder Apps."
baseurl: /index.md
permalink: pretty
github:
  is_project_page: false
footer:
  display: none
