theme: jekyll-theme-cayman
title: "Mein Schiff Bordfinder"
description: "Die offizielle Webseite der Bordfinder Apps."
permalink: /:categories/:year/:month/:day/:changelog:output_ext
github:
  is_project_page: false
footer:
  display: none
